### ISSUE TITLE
Make getting an item by id more convenient

### ISSUE THREAD

**Issue by justinfx** [voidshard/wysteria#20]
I've been having a quick play with the python API and one of the first things I noticed was that getting an item by a known id is a bit obscure. One must perform a search like:

```
s = client.Search()
s.params(id=someItemId)
ret = s.find_items()
item = ret[0]
```

If wysteria is meant to be an asset version tracking system, then it would seem to be quite common to need to reference items that are used in a pipeline. It might be very useful to have something like:

```
client.get_item(byId)
``` 

or something close to that, so that you can retrieve all of these objects when you know a reference id. Otherwise it involves constructing search objects and checking if the list is empty.

**Comment by justinfx** [comment]
After a little more thinking on this ticket I also thought I would add that fixing this would improve the caveat listed in the README, about searching not being consistent for up to a few seconds. The reason this caveat is there, is because all retrievals from the API go through the searchbase and there is no way to directly look things up from the database when you know the id/reference. If the API were expanded to have direct db lookups when you know the exact ids, then you can offer consistent lookups when a user does not need to search.

**Comment by voidshard** [comment]
Exactly! It would take a reshuffle of things in the server, but it should be doable

**Comment by justinfx** [comment]
It looks like the find methods use the search lookup to get back ids, and then ask the db to resolve them. Is it possible to just have methods that take ids and make this call directly?

https://github.com/voidshard/wysteria/blob/master/server/server.go#L436

**Comment by voidshard** [comment]
Yep the server could pull out "queries" that specify an ID and grab those, avoiding the search call. Sorry to be slow in replying -- we don't have internet at home yet (the phone company promises to send someone at least by the end of this month .. sigh ..).

**Comment by voidshard** [comment]
ID search branch is up, I'll add some client side sugar to get by ID

**Comment by voidshard** [comment]
Added client.Item(id) -- that makes it similar to client.Collection(some_identifier). Also added to Python client (but with the more pythonic "get_item")
