### ISSUE TITLE
Glide.yaml is broken + Readme needs working build instructions

### ISSUE THREAD

**Issue by justinfx** [voidshard/wysteria#8]
First off, for a new user there are no build instructions in the README. As a Go developer my first attempt is to "go get" the project, but this results in some issues pulling dependencies on my end. Then I see the Glide.yaml file, so I attempt to "glide i". But it appears the glide yaml contains a bunch of stdlib references when it shouldn't. Even after removing all of the stdlib packages, I still hit issues with glide trying to resolve the bleve package and its dependencies. Also it appears the elastic package is set to v2 while asking for version 5.x.

It would be ideal if the readme had clear instructions to build the server, especially for non-go developers. Additionally it would be good to clean up the glide yaml file and ensure `glide i` works properly with a fresh clone. Given that this is a server it may even be useful to actually vendor the dependencies so that users do not need the glide tool.

**Comment by justinfx** [comment]
Correction: `go get github.com/voidshard/wysteria/server` does work, by fetching all of the latest deps. Its just that the glide.yaml does not work, and the README needs clear build instructions :-)

**Comment by justinfx** [comment]
Merge #9 just contains the glide updates. Do you want to vendor the dependencies into the repo or just have people use glide (or rely on go get)?

**Comment by justinfx** [comment]
README updates also have been committed to #9

**Comment by voidshard** [comment]
Fair enough! I did start on build instructions last night (er, night before) but didn't complete. 

I'm fine with vendoring in the depends .. it probably will make building the server the most foolproof ..?
